services:
  agent-mcp:
    build: .
    ports:
      - "8000:8080"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - agent-network

  dashboard:
    build: .
    ports:
      - "3847:3847"
    working_dir: /app/agent_mcp/dashboard
    command: ["npm", "run", "dev"]
    depends_on:
      - agent-mcp
    restart: unless-stopped
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge